### ISSUE TITLE
Swift External Storage 0.1.0

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_primary_swift#2]
### Reason
- Initial marketplace release

### Open tasks
- [ ] https://github.com/owncloud/files_primary_swift/issues/1

### QA
- [ ] Create **QA Milestone**
- [ ] Move items from `development` to `qa` 
- [ ] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [ ] Bump version in info.xml
- [ ] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version'
- [ ] Create github tag for 'v$version'
- [ ] Build and sign tarball from github tag 'v$version'
- [ ] Smoke test tarball
- [ ] Upload to marketplace
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Rename QA milestone to '$version'
- [ ] Create PR to merge changes back to `master`
- [ ] On master, add a new 'Unreleased' section in CHANGELOG.md

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by PVince81** [comment]
I've converted this to a release ticket, so we know that there is WIP code on this app to be released at some point.

Maybe we could release this app first as is without any lib updates if that can save time.

**Comment by HanaGemela** [comment]
Closing this ticket and removing it from `Releases` project. In case a new release is needed, get in touch and reopen this ticket
